services:
  - type: web
    name: votoautomatizado
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn votoautomatizado.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: votoautomatizadodb
          property: connectionString
      - key: KHIPU_API_KEY
        sync: false
      - key: KHIPU_API_SECRET
        sync: false