services:
  - type: web
    name: votoautomatizado
    env: python
    buildCommand: "pip install -r requisitos.txt"
    startCommand: "gunicorn votoautomatizado.wsgi:application"
    envVars:
      DJANGO_SETTINGS_MODULE: votoautomatizado.settings
